# This is a basic workflow to help you get started with Actions

name: PR

# Controls when the workflow will run
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-pr-title@master
        with:
          regex: '\[[0-9]{2}\/[0-9]{2}\].+' # Regex the title should match.
          #allowed_prefixes: 'feature,fix,JIRA' # title should start with the given prefix
          #disallowed_prefixes: 'feat/,hotfix' # title should not start with the given prefix
          #prefix_case_sensitive: false # title prefix are case insensitive
          #min_length: 5 # Min length of the title
          #max_length: 20 # Max length of the title
          github_token: ${{ github.token }} # Default: ${{ github.token }}
