name: PR

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-pr-title@master
        with:
          regex: '\[[0-9]{1,2}\/[0-9]{1,2}\]' # Regex the title should match.
          
