# https://github.com/marketplace/actions/enforce-pr-labels
name: Enforce PR labels

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]
jobs:
  enforce-label:
    runs-on: ubuntu-latest
    steps:
    - uses: yogevbd/enforce-label-action@2.1.0
      with:
        REQUIRED_LABELS_ANY: "97-API/Front 同時リリース必須,98-API/Front 同時リリース不要"
